# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-27 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuff',
            name='user',
        ),
    ]
