# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-27 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_stuff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='user',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
