# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-27 16:38
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_stuff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='user',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=100),
        ),
    ]
