# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-28 04:14
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20171128_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='user',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=100),
        ),
    ]
