# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-28 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20171128_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='user',
            field=models.CharField(default='aaa', max_length=100),
        ),
    ]
