# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-28 11:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20171128_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
